<a href="https://colab.research.google.com/github/ENRIQUESPECTER/Mineria-de-Datos/blob/main/funciones_avanzadas_part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
import pandas as pd
df = pd.read_csv("part2_orders_a.csv")
df2 = pd.read_csv("part2_orders_b.csv")
df3 = pd.read_csv("part2_customers.csv")
df4 = pd.read_csv("part2_products.csv")

In [36]:
df.info()
df2.info()
df3.info()
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     6 non-null      int64
 1   order_date   6 non-null      object
 2   line_id      6 non-null      int64
 3   customer_id  6 non-null      object
 4   product_id   6 non-null      object
 5   qty          6 non-null      int64
 6   channel      6 non-null      object
dtypes: int64(3), object(4)
memory usage: 468.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     4 non-null      int64
 1   order_date   4 non-null      object
 2   line_id      4 non-null      int64
 3   customer_id  4 non-null      object
 4   product_id   4 non-null      object
 5   qty          4 non-null      int64
 6   channel      4 non-null      object
dtypes: int64(3), object(4)
memory usage: 356.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    8 non-null      object
 1   customer_name  8 non-null      object
 2   city           8 non-null      object
 3   segment        8 non-null      object
dtypes: object(4)
memory usage: 388.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   product_id  5 non-null      object
 1   product     5 non-null      object
 2   category    5 non-null      object
 3   unit_price  5 non-null      float64
dtypes: float64(1), object(3)
memory usage: 292.0+ bytes

In [37]:
df.head()

   order_id  order_date  line_id customer_id product_id  qty channel
0      2001  2026-01-02        1        C001        P10    2     web
1      2002  2026-01-02        2        C002        P20    1   store
2      2003  2026-01-03        3        C003        P20    3     web
3      2004  2026-01-04        4        C001        P30    1     app
4      2005  2026-01-05        5        C004        P10    5     web

In [38]:
df2.head()

   order_id  order_date  line_id customer_id product_id  qty channel
0      2007  2026-01-06        7        C002        P30    2     web
1      2008  2026-01-07        8        C006        P50    1     app
2      2009  2026-01-08        9        C007        P10    1     web
3      2010  2026-01-09       10        C008        P20    2   store

In [39]:
df3.head()

  customer_id customer_name  city    segment
0        C001           Ana  CDMX   Consumer
1        C002          Luis   GDL  Corporate
2        C003         Marta   MTY   Consumer
3        C004         Sofia   QRO  Small Biz
4        C005         Diego   GDL   Consumer

In [40]:
df4.head()

  product_id       product     category  unit_price
0        P10   USB-C Cable  Accessories         8.0
1        P20      Keyboard  Accessories        45.0
2        P30   Monitor 24"  Electronics       160.0
3        P40  Office Chair    Furniture       220.0
4        P50        Webcam  Electronics        70.0

**EJERCICIOS**

**Une orders_a y orders_b en un solo DataFrame orders con índice reiniciado.**

**Ordena orders por order_date ascendente y, en caso de empate, por qty descendente.**

**Establece order_date como índice en orders y ordena por índice (cronológico).**

In [56]:
orders = pd.concat([df,df2],ignore_index=True)
orders

   order_id  order_date  line_id customer_id product_id  qty channel
0      2001  2026-01-02        1        C001        P10    2     web
1      2002  2026-01-02        2        C002        P20    1   store
2      2003  2026-01-03        3        C003        P20    3     web
3      2004  2026-01-04        4        C001        P30    1     app
4      2005  2026-01-05        5        C004        P10    5     web
5      2006  2026-01-05        6        C005        P40    1   store
6      2007  2026-01-06        7        C002        P30    2     web
7      2008  2026-01-07        8        C006        P50    1     app
8      2009  2026-01-08        9        C007        P10    1     web
9      2010  2026-01-09       10        C008        P20    2   store

In [58]:
orders.sort_values(['order_date','qty'], ascending=[True,False])

   order_id  order_date  line_id customer_id product_id  qty channel
0      2001  2026-01-02        1        C001        P10    2     web
1      2002  2026-01-02        2        C002        P20    1   store
2      2003  2026-01-03        3        C003        P20    3     web
3      2004  2026-01-04        4        C001        P30    1     app
4      2005  2026-01-05        5        C004        P10    5     web
5      2006  2026-01-05        6        C005        P40    1   store
6      2007  2026-01-06        7        C002        P30    2     web
7      2008  2026-01-07        8        C006        P50    1     app
8      2009  2026-01-08        9        C007        P10    1     web
9      2010  2026-01-09       10        C008        P20    2   store

In [59]:
orders = orders.set_index('order_date')
orders.sort_index()

            order_id  line_id customer_id product_id  qty channel
order_date
2026-01-02      2001        1        C001        P10    2     web
2026-01-02      2002        2        C002        P20    1   store
2026-01-03      2003        3        C003        P20    3     web
2026-01-04      2004        4        C001        P30    1     app
2026-01-05      2005        5        C004        P10    5     web
2026-01-05      2006        6        C005        P40    1   store
2026-01-06      2007        7        C002        P30    2     web
2026-01-07      2008        8        C006        P50    1     app
2026-01-08      2009        9        C007        P10    1     web
2026-01-09      2010       10        C008        P20    2   store

**Merge (enriquecer órdenes con clientes):**

**Haz un merge para añadir a orders las columnas del cliente**
**(customer_name, city, segment) usando customer_id (left join). Valida que sea many_to_one.**

In [70]:
customers = (
    df3[['customer_id','customer_name','city','segment']]
)
customers

  customer_id customer_name  city    segment
0        C001           Ana  CDMX   Consumer
1        C002          Luis   GDL  Corporate
2        C003         Marta   MTY   Consumer
3        C004         Sofia   QRO  Small Biz
4        C005         Diego   GDL   Consumer
5        C006         Elena   MER   Consumer
6        C007         Paula   PUE  Corporate
7        C008         Ramon  CDMX  Small Biz

In [71]:
fusion = orders.merge(customers, on="customer_id", how="left", validate="many_to_one")
fusion

,order_id,line_id,customer_id,product_id,qty,channel,customer_name,city,segment
0,2001,1,C001,P10,2,web,Ana,CDMX,Consumer
1,2002,2,C002,P20,1,store,Luis,GDL,Corporate
2,2003,3,C003,P20,3,web,Marta,MTY,Consumer
3,2004,4,C001,P30,1,app,Ana,CDMX,Consumer
4,2005,5,C004,P10,5,web,Sofia,QRO,Small Biz
5,2006,6,C005,P40,1,store,Diego,GDL,Consumer
6,2007,7,C002,P30,2,web,Luis,GDL,Corporate
7,2008,8,C006,P50,1,app,Elena,MER,Consumer
8,2009,9,C007,P10,1,web,Paula,PUE,Corporate
9,2010,10,C008,P20,2,store,Ramon,CDMX,Small Biz

**Merge (añadir producto y calcular total):**

**Haz un merge adicional con products para añadir product, category, unit_price y crea una columna line_total = qty * unit_price. Luego ordena por line_total descendente y muestra top 5.**

In [80]:
products = df4

In [87]:
fusion = orders.merge(products, on='product_id', how='left', validate='many_to_one')
fusion['line_total'] = fusion['qty'] * fusion['unit_price']

fusion.sort_values("line_total", ascending=False)
fusion

,order_id,line_id,customer_id,product_id,qty,channel,product,category,unit_price,line_total
0,2001,1,C001,P10,2,web,USB-C Cable,Accessories,8.0,16.0
1,2002,2,C002,P20,1,store,Keyboard,Accessories,45.0,45.0
2,2003,3,C003,P20,3,web,Keyboard,Accessories,45.0,135.0
3,2004,4,C001,P30,1,app,"Monitor 24""",Electronics,160.0,160.0
4,2005,5,C004,P10,5,web,USB-C Cable,Accessories,8.0,40.0
5,2006,6,C005,P40,1,store,Office Chair,Furniture,220.0,220.0
6,2007,7,C002,P30,2,web,"Monitor 24""",Electronics,160.0,320.0
7,2008,8,C006,P50,1,app,Webcam,Electronics,70.0,70.0
8,2009,9,C007,P10,1,web,USB-C Cable,Accessories,8.0,8.0
9,2010,10,C008,P20,2,store,Keyboard,Accessories,45.0,90.0